(define (make-monitored f)
    (define count 0)
    (define (dispatch arg)
        (cond ((eq? arg 'how-many-calls?)
                    count)
                ((eq? arg 'reset-count)
                    ((set! count 0)))
                (else (f arg)
                        (set! count (+ count 1)))))
    dispatch)