(define (make-account balance pwd)
    (define (withdraw amount)
        (if (>= balance amount)
                (begin (set! balance (- balance amount)) balance)
                "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount)) 
        balance)
    (define (dispatch m p)
        (cond ((not (eq? p pwd)) "incorrect password")
                ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request: MAKE-ACCOUNT" m)))) 
    dispatch)