(define (make-account balance pwd)
    (define count 7)
    (define (withdraw amount)
        (if (>= balance amount)
                (begin (set! balance (- balance amount)) balance)
                "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount)) 
        balance)
    (define (dispatch m p)
        (if ((not (eq? p pwd)) (begin 
                                    (set! count (- count 1))
                                    "incorrect password"
                                    (if (eq? count 0)
                                        call-the-cops))
                                (set! count 7)))
        (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request: MAKE-ACCOUNT" m)))) 
    dispatch)